name: myaccount
description: Account manager
homepage: https://github.com/esgi-lyon/flutter-myaccount
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  bloc: ^8.0.3
  flutter_secure_storage: ^5.0.2

  hive: ^2.2.2
  shared_preferences: ^2.0.15
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  easy_localization: ^3.0.1
  google_fonts: 2.2.0
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.1.0
  date_field: ^3.0.1
  freezed: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.0.2
  mocktail: ^0.2.0
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:

  uses-material-design: true
  assets:
    - assets/translations/
  